"""
backend/vector_db.py

Vector Database for Chat History & Contextual Retrieval (RAG).
Uses SQLite as vector metadata & embedding store, with cosine similarity search
over dense vector embeddings generated by sentence-transformers or a fallback lightweight vectorizer.
"""

import os
import json
import sqlite3
import math
from datetime import datetime
from typing import List, Dict, Any, Optional

DB_PATH = os.path.join(os.path.dirname(__file__), "payroll.db")

# Initialize embedding model (SentenceTransformers with fallback)
_embedding_model = None

def get_embedding_model():
    global _embedding_model
    if _embedding_model is None:
        try:
            from sentence_transformers import SentenceTransformer
            # Lightweight 384-dimensional vector embedding model
            _embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
            print("VectorDB: Loaded SentenceTransformer ('all-MiniLM-L6-v2').")
        except Exception as e:
            print(f"VectorDB: SentenceTransformer not available ({e}). Using lightweight vectorizer.")
            _embedding_model = "fallback"
    return _embedding_model


def _compute_fallback_vector(text: str, dim: int = 128) -> List[float]:
    """Lightweight hash-based term frequency vector for fallback when sentence-transformers is offline."""
    words = [w.lower() for w in text.split() if len(w) > 1]
    vec = [0.0] * dim
    if not words:
        return vec
    for w in words:
        idx = hash(w) % dim
        vec[idx] += 1.0
    norm = math.sqrt(sum(x * x for x in vec))
    if norm > 0:
        vec = [x / norm for x in vec]
    return vec


def generate_embedding(text: str) -> List[float]:
    """Generate dense vector embedding for a given text string."""
    model = get_embedding_model()
    if model != "fallback" and hasattr(model, 'encode'):
        try:
            vector = model.encode(text, convert_to_numpy=True).tolist()
            return [float(x) for x in vector]
        except Exception as e:
            print(f"VectorDB: Error in sentence-transformer encode ({e}). Falling back.")
    return _compute_fallback_vector(text)


def cosine_similarity(vec1: List[float], vec2: List[float]) -> float:
    """Compute cosine similarity score between two dense vectors."""
    if not vec1 or not vec2 or len(vec1) != len(vec2):
        return 0.0
    dot_product = sum(a * b for a, b in zip(vec1, vec2))
    norm_a = math.sqrt(sum(a * a for a in vec1))
    norm_b = math.sqrt(sum(b * b for b in vec2))
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return dot_product / (norm_a * norm_b)


def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_vector_db():
    """Create chat_vector_store table in SQLite if it does not exist."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS chat_vector_store (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT NOT NULL,
        message_id TEXT NOT NULL,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        embedding TEXT NOT NULL,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    )
    """)
    cursor.execute("""
    CREATE INDEX IF NOT EXISTS idx_chat_vector_session ON chat_vector_store(session_id);
    """)
    conn.commit()
    conn.close()
    print("VectorDB: Table 'chat_vector_store' initialized successfully.")


def add_chat_message(session_id: str, message_id: str, role: str, content: str) -> Dict[str, Any]:
    """
    Generate vector embedding and store message into VectorDB for the given session_id.
    """
    if not session_id or not content.strip():
        return {}

    embedding = generate_embedding(content)
    embedding_json = json.dumps(embedding)
    now_iso = datetime.utcnow().isoformat()

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO chat_vector_store (session_id, message_id, role, content, embedding, timestamp)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (session_id, message_id, role, content, embedding_json, now_iso))
    
    conn.commit()
    inserted_id = cursor.lastrowid
    conn.close()

    return {
        "id": inserted_id,
        "session_id": session_id,
        "message_id": message_id,
        "role": role,
        "content": content,
        "timestamp": now_iso
    }


def get_session_messages(session_id: str) -> List[Dict[str, Any]]:
    """
    Retrieve all chat messages stored in VectorDB for a specific session_id in chronological order.
    """
    if not session_id:
        return []

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT message_id, role, content, timestamp
        FROM chat_vector_store
        WHERE session_id = ?
        ORDER BY id ASC
    """, (session_id,))
    
    rows = cursor.fetchall()
    conn.close()

    messages = []
    for r in rows:
        messages.append({
            "id": r["message_id"],
            "role": r["role"],
            "content": r["content"],
            "timestamp": r["timestamp"]
        })
    return messages


def search_relevant_history(session_id: str, query: str, top_k: int = 5) -> List[Dict[str, Any]]:
    """
    Perform vector similarity search against past messages in the active session.
    """
    if not session_id or not query.strip():
        return []

    query_vec = generate_embedding(query)

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT message_id, role, content, embedding, timestamp
        FROM chat_vector_store
        WHERE session_id = ?
    """, (session_id,))
    
    rows = cursor.fetchall()
    conn.close()

    scored_messages = []
    for r in rows:
        try:
            doc_vec = json.loads(r["embedding"])
            score = cosine_similarity(query_vec, doc_vec)
            scored_messages.append({
                "id": r["message_id"],
                "role": r["role"],
                "content": r["content"],
                "timestamp": r["timestamp"],
                "score": score
            })
        except Exception:
            continue

    # Sort by vector similarity score descending
    scored_messages.sort(key=lambda x: x["score"], reverse=True)
    return scored_messages[:top_k]


def delete_session_history(session_id: str) -> int:
    """
    Delete all vector records and message history for the specified session_id (used on logout).
    """
    if not session_id:
        return 0

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM chat_vector_store WHERE session_id = ?", (session_id,))
    deleted_count = cursor.rowcount
    conn.commit()
    conn.close()

    print(f"VectorDB: Purged {deleted_count} messages for session '{session_id}'.")
    return deleted_count
